# Generated by Django 3.1.1 on 2020-09-18 03:22

from django.db import migrations, models
import django.utils.timezone
import douara_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60)),
                ('cor', models.CharField(blank=True, max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=20)),
                ('lançamento', models.BooleanField(default=False, verbose_name='Terminado')),
                ('tamanho', models.CharField(blank=True, max_length=5)),
                ('preço', models.FloatField(blank=True, null=True)),
                ('promoção', models.FloatField(blank=True, null=True)),
                ('data_lançamento', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data de Lançamento')),
                ('imagem', models.ImageField(upload_to=douara_app.models.Produto.user_directory_path)),
            ],
        ),
    ]
