# Generated by Django 3.1.1 on 2020-09-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='lançamento',
            field=models.BooleanField(default=False),
        ),
    ]
