# Generated by Django 3.1.1 on 2020-09-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
