# Generated by Django 3.1.1 on 2020-09-21 02:04

from django.db import migrations, models
import douara_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0004_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_hover',
            field=models.ImageField(default=True, upload_to=douara_app.models.Produto.user_directory_path),
        ),
    ]
