# Generated by Django 3.1.1 on 2020-09-24 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0008_auto_20200924_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='user',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='data_do_carrinhho',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='Data de Formação'),
        ),
    ]
