# Generated by Django 3.1.1 on 2020-09-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0009_auto_20200924_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='data_do_carrinhho',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='douara_app.userprofile'),
        ),
    ]
