# Generated by Django 3.1.1 on 2020-09-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0010_auto_20200924_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
