# Generated by Django 3.1.1 on 2020-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0011_delete_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='CEP2',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
