# Generated by Django 3.1.1 on 2020-09-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0014_auto_20200924_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='quantidade',
        ),
    ]
