# Generated by Django 3.1.1 on 2020-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0015_remove_carrinho_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
