# Generated by Django 3.1.1 on 2020-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0016_carrinho_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descrição',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(blank=True, default=True, max_length=60, primary_key=True, serialize=False),
        ),
    ]
