# Generated by Django 3.1.1 on 2020-10-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douara_app', '0018_auto_20201001_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CPF_CNPJ',
            field=models.CharField(blank=True, max_length=18, primary_key=True, serialize=False),
        ),
    ]
